project:
  type: website
  output-dir: docs

website:
  title: "An Introduction to Git and Github in R"
  sidebar:
    style: "docked"
    contents: 
      - text: "Welcome"
        file: index.qmd
      - section: "Getting Started"
        contents: 
          - getting_started/installation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



