project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Git and Github with RStudio"
  repo-url: https://github.com/bcknr/IntroToGit
  repo-actions: issue
  page-navigation: true
  google-analytics: "G-C8C153PJMW"
  sidebar:
    tools: 
      - icon: github
        text: "GitHub"
        href: https://github.com/
    style: "docked"
    contents: 
      - text: "Welcome"
        file: index.qmd
      - section: "Getting Started"
        contents: 
          - getting_started/installation.qmd
          - getting_started/pat.qmd
          - getting_started/testlink.qmd
          - getting_started/questions.qmd
      - section: "Intro to Git/GitHub" 
        contents:
          - intro/whatisgit.qmd
          - intro/why.qmd
          - intro/workflow.qmd
          - intro/collab.qmd
          - intro/recover.qmd
      - section: "Activities"
        contents:
          - activities/create.qmd
          - activities/workflow_act.qmd
          - activities/collab_act.qmd
          - activities/recover_act.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



