project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Git and Github with RStudio"
  repo-url: https://github.com/bcknr/IntroToGit
  repo-actions: issue
  page-navigation: true
  sidebar:
    tools: 
      - icon: github
        text: "GitHub"
        href: https://github.com/
    style: "docked"
    contents: 
      - text: "Welcome"
        file: index.qmd
      - section: "Getting Started"
        contents: 
          - getting_started/installation.qmd
          - getting_started/pat.qmd
          - getting_started/testlink.qmd
          - getting_started/questions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



